#!/usr/bin/env bash

# Opções de editores.

editor="vim"

# Variaveis

data=$( date +'%d/%m/%Y' )

header="#!/usr/bin/env bash

# ---------------------------
# Script   : 
# Descrição:
# Versão   :
# Autor    : Lhordin
# Data	   : $data
# Licença  : GNU/GPL v3.0
# ---------------------------
# Uso:
# ---------------------------
"

# Testar se usuário passou o número certo de argumentos...
# ( 1 argumento ).

[[ $# -ne 1 ]] && echo "Apenas 1 nome de arquivo" && exit 1

# Testar se arquivo já existe...

[[ -f $1 ]] && echo "Esse arquivo já existe" && exit 1


echo "$header" > $1
chmod +x $1
$editor $1

exit 0
